Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model: {Precision: 'ap_fixed<16,6>', ReuseFactor: 1, Strategy: Latency}
IOType: io_parallel
KerasModel: !keras_model 'model_1/hls4ml_prj/keras_model.h5'
OutputDir: model_1/hls4ml_prj
ProjectName: myproject
Stamp: aA66489A
XilinxPart: xcu250-figd2104-2L-e
